Repository Soluto/tweek, pull requests merged in 2018-08, with the labels that each got.

#871 Replaced casbin with OPA
  services/gateway/Dockerfile
  services/gateway/Gopkg.lock
  services/gateway/Gopkg.toml
  services/gateway/appConfig/appConfig.go
  services/gateway/audit/auditor.go
  services/gateway/audit/logAuditor.go
  services/gateway/authorization.rego
  services/gateway/config/gateway.json
  services/gateway/config/gateway.local.json
  services/gateway/main.go
  services/gateway/model.conf
  services/gateway/security/authentication.go
  services/gateway/security/authorization.go
  services/gateway/security/authorization_test.go
  services/gateway/security/authorizer.go
  services/gateway/security/matchResource.go
  services/gateway/security/matchResource_test.go
  services/gateway/security/requestUtils.go
  services/gateway/security/requestUtils_test.go
  services/gateway/security/subjectExtractor.go
  services/gateway/security/subjectExtractor_test.go
  services/gateway/security/testdata/authorization.rego
  services/gateway/security/testdata/model.csv
  services/gateway/security/testdata/model2.csv
  services/gateway/security/testdata/policy.conf
  services/gateway/security/testdata/policy.json
  services/gateway/setup.go
  services/gateway/testdata/policy.json
  services/gateway/testdata/test_authorization.rego
  services/git-service/BareRepository/source/policy.csv
  services/git-service/BareRepository/source/policy.json
  services/git-service/BareRepository/tests-source/policy.csv
  services/git-service/BareRepository/tests-source/policy.json
  services/publishing/Tweek.Publishing.Service/Sync/Converters/PolicyConverter.cs
  services/publishing/Tweek.Publishing.Service/Validation/Patterns.cs
Labels: in progress

#879 fix no view model bug
  services/editor/src/components/common/Input/EditJSON.js
Labels: bug, services/editor

#880 Adapted policies endpoint in authoring for use with OPA
  e2e/integration/spec/authoring-api/policy.spec.js
  e2e/integration/spec/authoring-api/test-data/policy.csv
  e2e/integration/spec/authoring-api/test-data/policy.json
  services/authoring/src/repositories/policy-repository.ts
  services/authoring/src/routes/policies.ts
Labels: in progress

#881 Added rules extraction endpoint
  e2e/integration/spec/authoring-api/extractionRules.spec.js
  e2e/integration/spec/authoring-api/test-data/subject_extraction_rules.rego
  services/authoring/src/repositories/extraction-rules-repository.ts
  services/authoring/src/routes/config.ts
  services/authoring/src/routes/index.ts
  services/authoring/src/routes/subject-extraction-rules.ts
  services/authoring/src/server.ts
  services/gateway/security/authorizer.go
  services/gateway/security/subjectExtractor.go
  services/gateway/security/subjectExtractor_test.go
  services/gateway/security/testdata/subject_extraction_rules.rego
  services/gateway/setup.go
  services/git-service/BareRepository/source/subject_extractoin_rules.rego
  services/git-service/BareRepository/tests-source/subject_extraction_rules.rego
  services/publishing/Tweek.Publishing.Service/Sync/Converters/SubjectExtractionRulesConverter.cs
  services/publishing/Tweek.Publishing.Service/Validation/Patterns.cs
  services/publishing/Tweek.Publishing.Tests/Validation/SubjectExtractionValidatorTests.cs
Labels: in progress

#882 Added policy validation to publishing
  services/publishing/Tweek.Publishing.Service/Startup.cs
  services/publishing/Tweek.Publishing.Service/Tweek.Publishing.Service.csproj
  services/publishing/Tweek.Publishing.Service/Validation/PolicyValidationException.cs
  services/publishing/Tweek.Publishing.Service/Validation/PolicyValidator.cs
Labels: in progress

#586 added input validation when modifying context according to type schema
  CI/docker-compose.yml
  Tweek.sln
  core/Engine/Tweek.Engine.DataTypes/CustomTypeDefinition.cs
  core/Engine/Tweek.Engine.Drivers/Context/InputValidationContextDriver.cs
  core/Engine/Tweek.Engine.Drivers/Context/SchemaValidation.cs
  core/Engine/Tweek.Engine.Drivers/Utils/JsonValueExtensions.cs
  core/Engine/Tweek.Engine.Tests/Context/InputValidationContextDriverTests.cs
  core/Engine/Tweek.Engine.Tests/Context/schema.json
  core/Engine/Tweek.Engine.Tests/TestDrivers/InMemoryTestDriver.cs
  core/Engine/Tweek.Engine.Tests/Tweek.Engine.Tests.csproj
  deployments/dev/docker-compose.e2e.yml
  services/api/Tweek.ApiService.SmokeTests/ContextTests.cs
  services/api/Tweek.ApiService.SmokeTests/ITweekApi.cs
  services/api/Tweek.ApiService.SmokeTests/TweekApiServiceFactory.cs
  services/api/Tweek.ApiService/Controllers/ContextController.cs
  services/api/Tweek.ApiService/Startup.cs
  services/api/Tweek.ApiService/Tweek.ApiService.csproj
  services/api/Tweek.ApiService/appsettings.Development.json
  services/api/Tweek.ApiService/appsettings.json
  services/authoring/src/constants.ts
  services/authoring/src/server.ts
  services/authoring/src/utils/jsonLogger.ts
  services/editor/server/auth/providerSelector.js
  services/editor/server/authSupport.js
  services/editor/server/directoryProtection.js
  services/editor/server/index.js
  services/editor/server/utils/get-oauth2-user.js
  services/editor/spec/unit/server/utils/get-oauth2-user-spec.js
  services/editor/spec/unit/utils/key-name-validations-spec.js
  services/editor/src/components/common/EditableText/EditableText.js
  services/editor/src/components/common/SaveButton/SaveButton.js
  services/editor/src/index.js
  services/editor/src/pages/context/components/ContextPage/ContextPage.js
  services/editor/src/pages/keys/components/KeyPage/KeyAddPage/KeyFormatSelector.js
  services/editor/src/pages/keys/components/KeyPage/KeyAddPage/key-name-validations.js
  services/editor/src/pages/keys/components/KeyPage/KeyEditPage/KeyEditPage.js
  services/editor/src/pages/keys/components/KeysPage/KeysPage.js
  services/editor/src/pages/keys/components/utils/keyFormatHelpers.js
  services/editor/src/pages/settings/components/IdentityPage/IdentityProperty/IdentityProperty.js
  services/editor/src/pages/settings/components/SettingsPage/SettingsPage.js
  services/editor/src/registerServiceWorker.js
  services/editor/src/store/ducks/ducks-utils/guards.js
  services/git-service/BareRepository/source/manifests/@tweek/custom_types/version.json
  services/git-service/BareRepository/tests-source/manifests/@tweek/custom_types/version.json
  services/git-service/BareRepository/tests-source/manifests/@tweek/schema/test.json
Labels: in progress, services/api

#887 fix string comparison in schema validation
  core/Engine/Tweek.Engine.Drivers/Context/SchemaValidation.cs
  core/Engine/Tweek.Engine.Tests/Context/InputValidationContextDriverTests.cs
  core/Engine/Tweek.Engine.Tests/Context/schema.json
  services/api/Tweek.ApiService/Tweek.ApiService.csproj
Labels: bug, in progress, services/api

#888 fix logging
  core/Engine/Tweek.Engine.Drivers/Context/SchemaValidation.cs
  services/api/Tweek.ApiService/Tweek.ApiService.csproj
Labels: bug, in progress, services/api

#890 add log enrichment (serilog)
  services/api/Tweek.ApiService/Startup.cs
  services/api/Tweek.ApiService/Tweek.ApiService.csproj
  services/publishing/Tweek.Publishing.Service/Startup.cs
Labels: in progress, services/api, services/publishing

#884 added system.time_utc to editor
  services/editor/spec/unit/services/context-service-spec.js
  services/editor/src/components/JPadFullEditor/JPadVisualEditor/Matcher/Matcher.js
  services/editor/src/components/JPadFullEditor/JPadVisualEditor/Matcher/Properties/PropertyName.js
  services/editor/src/components/JPadFullEditor/JPadVisualEditor/Partition/PartitionsSelector.js
  services/editor/src/components/JPadFullEditor/JPadVisualEditor/PartitionsList/PartitionsList.js
  services/editor/src/services/context-service.js
Labels: in progress, services/editor

#896 Policies PATCH method added to authoring
  e2e/integration/package.json
  e2e/integration/spec/authoring-api/policy.spec.js
  e2e/integration/yarn.lock
  services/authoring/package.json
  services/authoring/src/repositories/policy-repository.ts
  services/authoring/src/routes/policies.ts
  services/authoring/src/server.ts
  services/authoring/src/utils/response-utils.ts
  services/authoring/swagger.config.json
  services/authoring/yarn.lock
  services/gateway/Gopkg.lock
  services/gateway/config/gateway.json
Labels: in progress

#903 Improved couchbase healthcheck by adding latency check
  addons/Context/Tweek.Drivers.Context.Couchbase/BucketConnectionHealthCheck.cs
  addons/Context/Tweek.Drivers.Context.Couchbase/CouchBaseServiceAddon.cs
  addons/Context/Tweek.Drivers.Context.Couchbase/Tweek.Drivers.Context.Couchbase.csproj
  services/api/Tweek.ApiService/Tweek.ApiService.csproj
Labels: in progress

#855 Gateway config moved to mounted volume
  CI/docker-compose.override.yml
  CI/docker-compose.yml
  deployments/dev/docker-compose.e2e.yml
  deployments/dev/docker-compose.local-editor.yml
  deployments/dev/docker-compose.override.yml
  deployments/dev/gateway/config/gateway.json
  deployments/dev/gateway/config/gateway.k8s.json
  deployments/dev/gateway/config/gateway.local-editor.json
  deployments/dev/gateway/config/gateway.local.json
  deployments/dev/gateway/config/gateway.test.json
  services/gateway/Dockerfile
  services/gateway/Makefile
  services/gateway/appConfig/appConfig.go
  services/gateway/settings/settings.json
  services/git-service/BareRepository/source/subject_extraction_rules.rego
Labels: in progress

#905 Decrease couchbase check duration
  addons/Context/Tweek.Drivers.Context.Couchbase/BucketConnectionHealthCheck.cs
  addons/Context/Tweek.Drivers.Context.Couchbase/CouchBaseServiceAddon.cs
  services/api/Tweek.ApiService/Tweek.ApiService.csproj
Labels: in progress

#907 set inital state to false
  addons/Context/Tweek.Drivers.Context.Couchbase/BucketConnectionHealthCheck.cs
  services/api/Tweek.ApiService/Tweek.ApiService.csproj
Labels: in progress

#908 add query healthcheck
  services/api/Tweek.ApiService/Diagnostics/QueryHealthCheck.cs
  services/api/Tweek.ApiService/Tweek.ApiService.csproj
Labels: in progress

#909 upgrading app metrics to 2.x
  .vscode/launch.json
  Tweek.sln
  addons/AppMetrics/Tweek.Addons.AppMetrics.GraphiteReporter/GraphiteNameFormatter.cs
  addons/AppMetrics/Tweek.Addons.AppMetrics.GraphiteReporter/GraphiteReporterAddon.cs
  addons/AppMetrics/Tweek.Addons.AppMetrics.GraphiteReporter/GraphiteSyntax.cs
  addons/AppMetrics/Tweek.Addons.AppMetrics.GraphiteReporter/Tweek.Addons.AppMetrics.GraphiteReporter.csproj
  addons/Context/Tweek.Drivers.Context.Couchbase/BucketConnectionHealthCheck.cs
  addons/Context/Tweek.Drivers.Context.Couchbase/CouchBaseServiceAddon.cs
  addons/Context/Tweek.Drivers.Context.Couchbase/Tweek.Drivers.Context.Couchbase.csproj
  core/Tweek.ApiService.Addons/Tweek.ApiService.Addons.csproj
  services/api/Tweek.ApiService/Diagnostics/EnvironmentHealthCheck.cs
  services/api/Tweek.ApiService/Diagnostics/QueryHealthCheck.cs
  services/api/Tweek.ApiService/Diagnostics/RulesRepositoryHealthCheck.cs
  services/api/Tweek.ApiService/Metrics/TimedContextDriver.cs
  services/api/Tweek.ApiService/Metrics/TimedRulesDriver.cs
  services/api/Tweek.ApiService/Program.cs
  services/api/Tweek.ApiService/Startup.cs
  services/api/Tweek.ApiService/Tweek.ApiService.csproj
  services/api/Tweek.ApiService/Utils/TimerOptionsExtentions.cs
  services/api/Tweek.ApiService/appsettings.json
Labels: in progress

#910 Add local http health check
  services/api/Tweek.ApiService/Diagnostics/LocalHttpHealthCheck.cs
  services/api/Tweek.ApiService/Tweek.ApiService.csproj
Labels: in progress

#911 Publishing git permissions fix
  services/publishing/Tweek.Publishing.Service/Handlers/ValidationHandler.cs
  services/publishing/Tweek.Publishing.Service/Startup.cs
  services/publishing/Tweek.Publishing.Service/Tweek.Publishing.Service.csproj
  services/publishing/Tweek.Publishing.Service/appsettings.json
Labels: in progress

#912 add support for untyped arrays in editor
  e2e/ui/spec/keys/edit-key.js
  services/editor/package.json
  services/editor/src/components/common/Input/EditJSON.js
  services/editor/src/components/common/Input/TypedInput.js
  services/editor/src/services/types-service.js
Labels: in progress

#899 Swagger for gateway
  CI/docker-compose.yml
  deployments/dev/gateway/config/gateway.k8s.json
  deployments/dev/gateway/config/gateway.local-editor.json
  deployments/dev/gateway/config/gateway.test.json
  e2e/integration/package.json
  e2e/integration/spec/authoring-api/policy.spec.js
  e2e/integration/spec/gateway/v2.spec.js
  e2e/integration/spec/gateway/v2_app_policies.spec.js
  e2e/integration/yarn.lock
  services/authoring/src/repositories/git-repository.ts
  services/authoring/src/routes/schema.ts
  services/authoring/test/keys-repository-spec.ts
  services/authoring/yarn.lock
  services/editor/yarn.lock
  services/gateway/Gopkg.lock
  services/gateway/appConfig/appConfig.go
  services/gateway/audit/logAuditor.go
  services/gateway/externalApps/externalApps.go
  services/gateway/handlers/statusHandler.go
  services/gateway/main.go
  services/gateway/security/ResourceDeffinition.md
  services/gateway/security/authRouter.go
  services/gateway/security/authentication.go
  services/gateway/security/authorization.go
  services/gateway/security/authorization_test.go
  services/gateway/security/authorizer.go
  services/gateway/security/requestUtils.go
  services/gateway/security/requestUtils_test.go
  services/gateway/security/testdata/policy.json
  services/gateway/settings/settings.json
  services/gateway/swagger.yml
  services/gateway/utils/arrayUtils.go
  services/git-service/BareRepository/source/policy.json
  services/git-service/BareRepository/tests-source/policy.json
  services/publishing/Tweek.Publishing.Service/Sync/Converters/ExternalAppsConverter.cs
Labels: in progress
