Repository Soluto/tweek, pull requests merged in 2018-07, with the labels that each got.

#848 847 update dotnet core services
  .circleci/config.yml
  .gitignore
  .vscode/launch.json
  TweekApiDockerfile
  TweekApiSmokeTestDockerfile
  addons/Context/Tweek.Drivers.Context.Couchbase.IntegrationTests/Tweek.Drivers.Context.Couchbase.IntegrationTests.csproj
  addons/Context/Tweek.Drivers.Context.Couchbase/Tweek.Drivers.Context.Couchbase.csproj
  addons/Context/Tweek.Drivers.Context.MongoDb.IntegrationTests/Tweek.Drivers.Context.MongoDb.IntegrationTests.csproj
  addons/Context/Tweek.Drivers.Context.MongoDb/Tweek.Drivers.Context.MongoDb.csproj
  addons/Context/Tweek.Drivers.Context.Redis.IntegrationTests/Tweek.Drivers.Context.Redis.IntegrationTests.csproj
  addons/Rules/Tweek.Drivers.Rules.Management/Tweek.Drivers.Rules.Management.csproj
  addons/Rules/Tweek.Drivers.Rules.Minio/Tweek.Drivers.Rules.Minio.csproj
  core/Engine/Tweek.Engine.Core/Tweek.Engine.Core.csproj
  core/Engine/Tweek.Engine.Core/Utils/TraceHelpers.cs
  core/Engine/Tweek.Engine.Drivers/Tweek.Engine.Drivers.csproj
  core/Engine/Tweek.Engine.Tests/Tweek.Engine.Tests.csproj
  core/Engine/Tweek.Engine/Tweek.Engine.csproj
  core/JPad/Tweek.JPad.Utils/Tweek.JPad.Utils.csproj
  core/Tweek.ApiService.Addons/Tweek.ApiService.Addons.csproj
  services/api/Tweek.ApiService.SmokeTests/Tweek.ApiService.SmokeTests.csproj
  services/api/Tweek.ApiService.Tests/Tweek.ApiService.Tests.csproj
  services/api/Tweek.ApiService/Program.cs
  services/api/Tweek.ApiService/Tweek.ApiService.csproj
  services/api/Tweek.ApiService/web.config
  services/publishing/Dockerfile
  services/publishing/Tweek.Publishing.Service/Startup.cs
  services/publishing/Tweek.Publishing.Service/Sync/RepoSynchronizer.cs
  services/publishing/Tweek.Publishing.Service/Sync/SyncActor.cs
  services/publishing/Tweek.Publishing.Service/Tweek.Publishing.Service.csproj
  services/publishing/Tweek.Publishing.Service/Utils/ShellHelper.cs
  services/publishing/Tweek.Publishing.Tests/Tweek.Publishing.Tests.csproj
Labels: in progress

#850 Update Tweek.Addons.ApplicationInsights.csproj
  addons/ApplicationInsights/Tweek.Addons.ApplicationInsights/Tweek.Addons.ApplicationInsights.csproj
Labels: in progress, services/api

#849 845 rules update error handling
  .vscode/launch.json
  TweekApiDockerfile
  core/Engine/Tweek.Engine.Core/Utils/TraceHelpers.cs
  core/Engine/Tweek.Engine.Drivers/Rules/IRulesRepository.cs
  core/Engine/Tweek.Engine.Drivers/Rules/RulesRepository.cs
  core/Engine/Tweek.Engine.Tests/TestDrivers/InMemoryTestDriver.cs
  core/Engine/Tweek.Engine/Rules/Creation/RulesLoader.cs
  deployments/dev/docker-compose.e2e.yml
  deployments/dev/docker-compose.override.yml
  services/api/Tweek.ApiService/Diagnostics/RulesRepositoryHealthCheck.cs
  services/api/Tweek.ApiService/Tweek.ApiService.csproj
  services/api/Tweek.ApiService/appsettings.Development.json
  services/api/Tweek.ApiService/appsettings.json
Labels: bug, in progress, services/api

#852 Fix OAuth2 Identity
  services/editor/package.json
  services/editor/server/auth/oauth2.js
  services/editor/server/utils/get-oauth2-user.js
  services/editor/spec/unit/server/utils/get-oauth2-user-spec.js
Labels: in progress

#854 Remove management
  CONTRIBUTING.md
  Tweek.sln
  addons/Rules/Tweek.Drivers.Rules.Management/HttpUtils.cs
  addons/Rules/Tweek.Drivers.Rules.Management/ManagementRulesDriver.cs
  addons/Rules/Tweek.Drivers.Rules.Management/RulesManagementAddon.cs
  addons/Rules/Tweek.Drivers.Rules.Management/Tweek.Drivers.Rules.Management.csproj
  services/api/Tweek.ApiService/Tweek.ApiService.csproj
  services/api/Tweek.ApiService/appsettings.json
  services/publishing/Tweek.Publishing.Service/Tweek.Publishing.Service.csproj
Labels: in progress, services/api, services/publishing

#790 add better failure handling for state promises in authoring index
  services/authoring/package.json
  services/authoring/src/search-index/index.ts
Labels: bug, in progress, services/authoring

#857 838 - Allow credentials should be always true
  CI/docker-compose.yml
  deployments/dev/docker-compose.override.yml
  deployments/kubernetes/gateway.yaml
  services/gateway/appConfig/appConfig.go
  services/gateway/corsSupport/corsSupport.go
Labels: in progress

#856 Set editor backend url properly
  deployments/dev/docker-compose.e2e.yml
  deployments/dev/docker-compose.local-editor.yml
  deployments/dev/docker-compose.override.yml
  deployments/dev/editor/local/config/envVars.js
  deployments/dev/editor/test/config/envVars.js
  services/editor/index.js
  services/editor/public/index.html
  services/editor/src/pages/login/components/BasicAuthLoginButton.js
  services/editor/src/utils/fetch.js
Labels: in progress

#860 846 Controller for gateway that returns status of all services
  services/gateway/Gopkg.lock
  services/gateway/Makefile
  services/gateway/handlers/statusHandler.go
  services/gateway/handlers/statusHandler_test.go
  services/gateway/main.go
Labels: in progress

#864 862 - Publishing validates sub extraction rules while sync to minio
  services/publishing/Dockerfile
  services/publishing/Tweek.Publishing.Service/Handlers/PushHandler.cs
  services/publishing/Tweek.Publishing.Service/Startup.cs
  services/publishing/Tweek.Publishing.Service/Sync/Converters/SubjectExtractionRulesConverter.cs
  services/publishing/Tweek.Publishing.Service/Validation/Patterns.cs
  services/publishing/Tweek.Publishing.Service/Validation/SubjectExtractionRulesValidationException.cs
  services/publishing/Tweek.Publishing.Service/Validation/SubjectExtractionValidator.cs
  services/publishing/Tweek.Publishing.Tests/Validation/SubjectExtractionValidatorTests.cs
Labels: in progress
