Repository Soluto/tweek, pull requests merged in 2018-02, with the labels that each got.

#763 Resharper publishing
  services/publishing/Tweek.Publishing.Service/Handlers/SyncHandler.cs
  services/publishing/Tweek.Publishing.Service/Handlers/ValidationHandler.cs
  services/publishing/Tweek.Publishing.Service/Messaging/IntervalPublisher.cs
  services/publishing/Tweek.Publishing.Service/Messaging/NatsPublisher.cs
  services/publishing/Tweek.Publishing.Service/Packing/KeyDef.cs
  services/publishing/Tweek.Publishing.Service/Packing/Manifest.cs
  services/publishing/Tweek.Publishing.Service/Packing/Packer.cs
  services/publishing/Tweek.Publishing.Service/Packing/VersionsBlob.cs
  services/publishing/Tweek.Publishing.Service/Program.cs
  services/publishing/Tweek.Publishing.Service/Startup.cs
  services/publishing/Tweek.Publishing.Service/Storage/IObjectStorage.cs
  services/publishing/Tweek.Publishing.Service/Storage/MinioBucketStorage.cs
  services/publishing/Tweek.Publishing.Service/Storage/ObjectStorageExtenstions.cs
  services/publishing/Tweek.Publishing.Service/Sync/RepoSynchronizer.cs
  services/publishing/Tweek.Publishing.Service/Sync/StorageSynchronizer.cs
  services/publishing/Tweek.Publishing.Service/Utils/ConfigurationHelper.cs
  services/publishing/Tweek.Publishing.Service/Utils/ShellHelper.cs
  services/publishing/Tweek.Publishing.Service/Validation/CircularDependencyValidator.cs
  services/publishing/Tweek.Publishing.Service/Validation/CircularValidationException.cs
  services/publishing/Tweek.Publishing.Service/Validation/CompileJPadValidator.cs
  services/publishing/Tweek.Publishing.Service/Validation/GitValidationFlow.cs
  services/publishing/Tweek.Publishing.Service/Validation/IValidator.cs
  services/publishing/Tweek.Publishing.Tests/PackerTests.cs
  services/publishing/Tweek.Publishing.Tests/Validation/CircularDependencyValidatorTests.cs
  services/publishing/Tweek.Publishing.Tests/Validation/GitValidationFlowTests.cs
Labels: in progress

#743 CORS support added to secure-gateway
  CI/docker-compose.yml
  deployments/dev/docker-compose.override.yml
  e2e/integration/package.json
  e2e/integration/spec/secure-gateway/v2_cors.spec.js
  e2e/integration/yarn.lock
  services/secure-gateway/Gopkg.lock
  services/secure-gateway/appConfig/appConfig.go
  services/secure-gateway/config/gateway.local.json
  services/secure-gateway/corsSupport/corsSupport.go
  services/secure-gateway/main.go
  services/secure-gateway/transformation/transformation.go
Labels: in progress

#766 add attempt to fix integration tests
  core/Engine/Tweek.Engine/Rules/Creation/RulesLoader.cs
  e2e/integration/spec/authoring-api/bulk-keys-upload.spec.js
Labels: in progress

#767 small fix of repo_location param and usage in validation scenarios
  services/publishing/Tweek.Publishing.Service/Handlers/ValidationHandler.cs
  services/publishing/Tweek.Publishing.Service/Startup.cs
  services/publishing/Tweek.Publishing.Service/Sync/RepoSynchronizer.cs
  services/publishing/Tweek.Publishing.Service/Tweek.Publishing.Service.csproj
  services/publishing/hooks/post-receive
  services/publishing/scripts/init-git.sh
  services/publishing/scripts/ssh-helper.sh
Labels: in progress

#771 fix - publishing set post-receive to work sync
  services/publishing/Tweek.Publishing.Service/Tweek.Publishing.Service.csproj
  services/publishing/hooks/post-receive
Labels: in progress

#773 Update sshd_config
  services/publishing/Tweek.Publishing.Service/Tweek.Publishing.Service.csproj
  services/publishing/scripts/sshd_config
Labels: in progress

#774 Update sshd_config
  services/publishing/Tweek.Publishing.Service/Tweek.Publishing.Service.csproj
  services/publishing/scripts/sshd_config
Labels: in progress

#762 738 policies
  CI/docker-compose.yml
  e2e/integration/spec/authoring-api/policy.spec.js
  services/api/Tweek.ApiService.SmokeTests/test.sh
  services/git-service/BareRepository/source/policy.csv
  services/git-service/BareRepository/tests-source/policy.csv
  services/secure-gateway/Gopkg.lock
  services/secure-gateway/audit/auditor.go
  services/secure-gateway/config/gateway.local.json
  services/secure-gateway/handlers/models_test.go
  services/secure-gateway/model.conf
  services/secure-gateway/security/ResourceDeffinition.md
  services/secure-gateway/security/authorization.go
  services/secure-gateway/security/authorization_test.go
  services/secure-gateway/security/extractFromRequest.go
  services/secure-gateway/security/extractFromRequest_test.go
  services/secure-gateway/security/matchResource.go
  services/secure-gateway/security/matchResource_test.go
  services/secure-gateway/security/requestUtils.go
  services/secure-gateway/security/requestUtils_test.go
  services/secure-gateway/security/testdata/model.csv
  services/secure-gateway/security/testdata/model2.csv
  services/secure-gateway/security/testdata/policy.conf
Labels: in progress

#777 775 authorize tweek issuer by issuer w/o email check
  e2e/ui/clients/AuthenticatedClient.js
  services/editor/server/auth/generateToken.js
  services/secure-gateway/security/authentication.go
  services/secure-gateway/security/authorization.go
  services/secure-gateway/security/jwtUtils.go
  services/secure-gateway/transformation/tags_test.go
Labels: in progress

#779 Publishing safer minio check
  services/publishing/Tweek.Publishing.Service/Startup.cs
  services/publishing/Tweek.Publishing.Service/Storage/IObjectStorage.cs
  services/publishing/Tweek.Publishing.Service/Storage/MinioBucketStorage.cs
  services/publishing/Tweek.Publishing.Service/Sync/SyncActor.cs
  services/publishing/Tweek.Publishing.Service/Tweek.Publishing.Service.csproj
Labels: in progress

#783 Fix empty override key scenario
  core/Engine/Tweek.Engine.Tests/EngineTests.cs
  core/Engine/Tweek.Engine/Api.cs
  services/editor/src/pages/context/components/FixedKeys/FixedKeysList/FixedKey/FixedKey.js
Labels: bug, in progress, services/api, services/editor

#785 hack for fixing sshd defunct processes
  services/publishing/Dockerfile
  services/publishing/Tweek.Publishing.Service/Startup.cs
Labels: in progress

#788 fix #786
  services/publishing/Tweek.Publishing.Service/Tweek.Publishing.Service.csproj
  services/publishing/scripts/init-git.sh
Labels: in progress, services/publishing
