Repository Soluto/tweek, pull requests merged in 2019-01, with the labels that each got.

#1045 Using logrus for logging instead of the default golang log in gateway
  services/gateway/Gopkg.lock
  services/gateway/Gopkg.toml
  services/gateway/appConfig/appConfig.go
  services/gateway/audit/logAuditor.go
  services/gateway/externalApps/externalApps.go
  services/gateway/handlers/statusHandler.go
  services/gateway/main.go
  services/gateway/passThrough/passThrough.go
  services/gateway/security/authRouter.go
  services/gateway/security/authentication.go
  services/gateway/security/authorization.go
  services/gateway/security/authorizer.go
  services/gateway/security/jwkCache.go
  services/gateway/security/jwtUtils.go
  services/gateway/security/subjectExtractor.go
  services/gateway/security/userinfo.go
  services/gateway/setup.go
  services/gateway/swagger.go
  services/gateway/transformation/health.go
  services/gateway/transformation/transformation.go
Labels: in progress

#1055 Update ValidationIcon.js
  services/editor/package.json
  services/editor/src/components/common/ValidationIcon.js
Labels: bug, in progress

#1054 Add skaffold for local development
  TweekApi.Dockerfile
  deployments/kubernetes/README.md
  deployments/kubernetes/api.yaml
  deployments/kubernetes/authoring.yaml
  deployments/kubernetes/editor.yaml
  deployments/kubernetes/gateway.yaml
  deployments/kubernetes/git.yaml
  deployments/kubernetes/infra/gateway-config.yaml
  deployments/kubernetes/infra/minio.yaml
  deployments/kubernetes/infra/nats.yaml
  deployments/kubernetes/infra/oidc-server-mock.yaml
  deployments/kubernetes/infra/redis.yaml
  deployments/kubernetes/infra/tweek-secrets.yaml
  deployments/kubernetes/publishing.yaml
  deployments/kubernetes/skaffold.yaml
Labels: in progress

#1027 Truncate keys in editor UI
  services/editor/src/pages/keys/components/KeysList/KeysList.css
  services/editor/src/pages/keys/components/KeysList/KeysList.js
  services/editor/src/pages/keys/components/KeysList/KeysList.less
Labels: UX, in progress, services/editor

#1058 Upgraded editor node to version 10
  services/editor/Dockerfile
  services/editor/package.json
  services/editor/src/index.js
  services/editor/yarn.lock
Labels: in progress

#1072 add logout button
  README.md
  services/editor/package.json
  services/editor/src/Routes.js
  services/editor/src/components/App.css
  services/editor/src/components/App.less
  services/editor/src/components/AppHeader.js
  services/editor/src/components/UserBar.js
  services/editor/src/services/auth-service.js
  services/editor/yarn.lock
  services/gateway/Dockerfile
  services/gateway/security/userinfo.go
Labels: UX, in progress, security, services/editor

#1073 disable v1 read/write api access by default repo
  services/git-service/BareRepository/source/implementations/jpad/@tweek/auth/@global/read_configuration.jpad
  services/git-service/BareRepository/source/implementations/jpad/@tweek/auth/@global/write_context.jpad
Labels: in progress

#1074 1059 docs
  docs/CNAME
  docs/Gemfile
  docs/Gemfile.lock
  docs/_config.yml
  docs/_includes/_sidemenu_rec.html
  docs/_includes/header.html
  docs/_includes/sidemenu.html
  docs/_layouts/default.html
  docs/_layouts/home.html
  docs/assets/folder-icon-closed.svg
  docs/assets/folder-icon-opened.svg
  docs/assets/inverted-logo.png
  docs/assets/logo-with-background.png
  docs/assets/logo.svg
  docs/assets/main.scss
  docs/assets/tweek.png
  docs/docker-compose.yml
  docs/index.md
  docs/pages/1.getting-started/01.first-setup.md
  docs/pages/1.getting-started/02.using-tweek.md
  docs/pages/2.concepts/context/intro-to-context.md
  docs/pages/2.concepts/context/schema.md
  docs/pages/2.concepts/keys/keys-and-paths.md
  docs/pages/3.deployment/01.basic.md
  docs/pages/3.deployment/02.configuration/01.api.md
  docs/pages/3.deployment/02.configuration/02.editor.md
Labels: documentation, in progress

#1077 update docs
  README.md
  docs/pages/2.concepts/01.keys/keys-and-paths.md
  docs/pages/2.concepts/02.context/intro-to-context.md
  docs/pages/2.concepts/02.context/schema.md
  docs/pages/2.concepts/03.security/01.intro.md
  docs/pages/3.deployment/02.configuration/01.api.md
  docs/pages/3.deployment/02.configuration/02.editor.md
  docs/pages/3.deployment/02.configuration/02.gateway.md
Labels: in progress

#1075 some swagger improvements, remove revsion path from authoring, update…
  e2e/integration/spec/gateway/v2.spec.js
  services/authoring/src/routes/keys.ts
  services/gateway/Dockerfile
  services/gateway/go.mod
  services/gateway/go.sum
  services/gateway/main.go
  services/gateway/settings/settings.json
  services/gateway/swagger.go
  services/gateway/swagger/openapi.yaml
  services/gateway/swagger/swagger.yml
  services/gateway/transformation/transformation.go
Labels: in progress

#1085 [editor] upgrade dev dependencies
  package.json
  services/editor/Dockerfile
  services/editor/package.json
  services/editor/src/components/JPadFullEditor/rules-utils.spec.js
  services/editor/src/components/common/ErrorHandler.spec.js
  services/editor/src/components/common/__snapshots__/ErrorHandler.spec.js.snap
  services/editor/src/pages/keys/components/KeyPage/KeyAddPage/key-name-validations.spec.js
  services/editor/src/services/auth-service.spec.js
  services/editor/src/services/context-service.spec.js
  services/editor/src/services/operators-provider.spec.js
  services/editor/src/services/types-services.spec.js
  services/editor/src/store/ducks/ducks-utils/validations/key-value-type-validations.spec.js
  services/editor/src/store/ducks/schema.spec.js
  services/editor/src/store/ducks/selectedKey.spec.js
  services/editor/src/utils/mutator.spec.js
  services/editor/yarn.lock
  yarn.lock
Labels: in progress

#1086 [editor] Use official tweek clients
  services/editor/package.json
  services/editor/src/components/App.js
  services/editor/src/components/JPadFullEditor/JPadVisualEditor/Matcher/Properties/PropertyComboBox.js
  services/editor/src/components/UserBar.js
  services/editor/src/components/common/ComboBox/AutoSuggest.js
  services/editor/src/components/common/ComboBox/MultiSourceComboBox.js
  services/editor/src/components/googleTagManager.js
  services/editor/src/contexts/CurrentUser.js
  services/editor/src/contexts/Tweek.js
  services/editor/src/hoc/with-search-config.js
  services/editor/src/pages/context/components/IdentityProperties/IdentityProperties.js
  services/editor/src/pages/keys/components/KeyPage/KeyAddPage/NewKeyInput.js
  services/editor/src/pages/keys/components/KeyPage/KeyEditPage/KeyPageActions/KeyPageActions.js
  services/editor/src/pages/keys/components/KeyPage/KeyPage.js
  services/editor/src/pages/keys/components/KeysList/KeysList.js
  services/editor/src/pages/login/components/BasicAuthLoginButton.js
  services/editor/src/pages/login/components/LoginPage.js
  services/editor/src/pages/settings/components/SettingsPage/Versions.js
  services/editor/src/services/auth-service.js
  services/editor/src/services/auth-service.spec.js
  services/editor/src/services/context-service.js
  services/editor/src/services/context-service.spec.js
  services/editor/src/services/search-service.js
  services/editor/src/services/types-service.js
  services/editor/src/services/types-services.spec.js
  services/editor/src/store/ducks/context.js
  services/editor/src/store/ducks/keys.js
  services/editor/src/store/ducks/schema.js
  services/editor/src/store/ducks/schema.spec.js
  services/editor/src/store/ducks/selectedKey.js
  services/editor/src/store/ducks/selectedKey.spec.js
  services/editor/src/store/ducks/tags.js
  services/editor/src/utils/fetch.js
  services/editor/src/utils/http.js
  services/editor/src/utils/tweekClients.js
  services/editor/yarn.lock
Labels: in progress

#1088 Fixed editing key after viewing old revisions
  services/editor/src/pages/keys/components/KeyPage/KeyEditPage/RevisionHistory/RevisionHistory.js
Labels: in progress

#1089 Update LoginPage.js
  deployments/dev/docker-compose.local-editor.yml
  deployments/dev/gateway/config/gateway.local-editor.json
  services/editor/package.json
  services/editor/src/pages/login/components/LoginPage.js
Labels: UX, bug, in progress, services/editor
