Repository Soluto/tweek, pull requests merged in 2019-02, with the labels that each got.

#1090 fix
  services/gateway/externalApps/externalApps.go
  services/gateway/version.go
Labels: bug, in progress, services/gateway

#1095 [gateway] fix delete context authorization
  services/gateway/security/authorization_test.go
  services/gateway/security/requestUtils.go
  services/gateway/security/requestUtils_test.go
Labels: in progress

#1096 Improve integration tests
  CI/codefresh.yml
  CI/docker-compose.override.yml
  deployments/dev/docker-compose.e2e.yml
  e2e/integration/package.json
  e2e/integration/spec/authoring-api/bulk-keys-upload.spec.js
  e2e/integration/spec/authoring-api/extractionRules.spec.js
  e2e/integration/spec/authoring-api/policy.spec.js
  e2e/integration/spec/authoring-api/write-validation.spec.js
  e2e/integration/spec/gateway/v2.spec.js
  e2e/integration/spec/gateway/v2_app_policies.spec.js
  e2e/integration/spec/gateway/v2_cors.spec.js
  e2e/integration/spec/setup.js
  e2e/integration/spec/tweek-api/delete-context.test.js
  e2e/integration/spec/tweek-api/key-aliases.test.js
  e2e/integration/spec/tweek-api/value-distribution.test.js
  e2e/integration/utils/client.js
  e2e/integration/utils/clients.js
  e2e/integration/utils/getToken.js
  e2e/integration/utils/minio.js
  e2e/integration/yarn.lock
  services/gateway/.dockerignore
  services/gateway/externalApps/externalApps.go
  services/gateway/security/authentication.go
  services/gateway/security/authorization.go
  services/gateway/setup.go
Labels: in progress

#1098 Embed pwt in docs
  docs/_includes/_sidemenu_rec.html
  docs/_layouts/play-with-tweek.html
  docs/assets/main.scss
  docs/pages/1.getting-started/01.first-setup.md
  docs/pages/1.getting-started/02.using-tweek.md
  docs/pages/play-with-tweek.md
Labels: documentation, in progress

#1099 fix lock issue in status handler
  services/gateway/handlers/statusHandler.go
  services/gateway/version.go
Labels: in progress

#1103 Update googleTagManager.js
  services/editor/package.json
  services/editor/src/components/googleTagManager.js
Labels: in progress, services/editor

#1104 Update googleTagManager.js
  services/editor/package.json
  services/editor/src/components/googleTagManager.js
Labels: in progress, services/editor

#1106 [editor] upgrade react-tweek package
  services/editor/package.json
  services/editor/src/components/googleTagManager.js
  services/editor/src/hoc/with-search-config.js
  services/editor/src/pages/keys/components/KeyPage/KeyAddPage/NewKeyInput.js
  services/editor/src/pages/keys/components/KeyPage/KeyEditPage/KeyPageActions/KeyPageActions.js
  services/editor/src/pages/keys/components/KeyPage/KeyPage.js
  services/editor/src/pages/keys/components/KeysList/KeysList.js
  services/editor/yarn.lock
Labels: in progress

#1108 [editor] Upgrade editor packages
  e2e/ui/spec/context/override-keys.js
  e2e/ui/spec/keys/edit-const-key.js
  e2e/ui/spec/validations/key-name-validations.js
  services/editor/config-overrides.js
  services/editor/package.json
  services/editor/src/Routes.js
  services/editor/src/components/JPadFullEditor/JPadVisualEditor/Partition/PartitionsSelector.js
  services/editor/src/components/UserBar.js
  services/editor/src/components/common/Input/ListTypedValue.js
  services/editor/src/pages/context/components/FixedKeys/FixedKeys.js
  services/editor/src/pages/keys/components/KeyPage/KeyEditPage/KeyTags/KeyTags.js
  services/editor/src/pages/keys/components/KeyPage/KeyEditPage/RevisionHistory/RevisionHistory.js
  services/editor/src/pages/login/components/AzureLoggedInPage.js
  services/editor/src/pages/login/components/BasicAuthLoggedInPage.js
  services/editor/src/pages/login/components/BasicAuthLoginButton.js
  services/editor/src/pages/login/components/LoggedInPage.js
  services/editor/src/pages/login/components/LoginPage.js
  services/editor/src/pages/login/components/SilentLoggedInPage.js
  services/editor/src/pages/settings/components/SettingsPage/Versions.js
  services/editor/src/store/browserHistory.js
  services/editor/src/store/configureStore.js
  services/editor/src/store/ducks/context.js
  services/editor/src/store/ducks/schema.js
  services/editor/src/store/ducks/schema.spec.js
  services/editor/src/store/ducks/selectedKey.js
  services/editor/src/store/ducks/tags.js
  services/editor/src/store/rootReducer.js
  services/editor/src/utils/tweekClients.js
  services/editor/yarn.lock
Labels: in progress

#1114 fixed tweek-management client timeout and format properly fetchError
  services/editor/src/store/ducks/notifications.js
  services/editor/src/utils/tweekClients.js
Labels: bug, in progress, services/editor

#1115 Added code to output basic auth password after keys generation
  utils/generate_keys.sh
Labels: in progress

#1109 Jwt policies min ui
  deployments/dev/docker-compose.local-editor.yml
  docs/pages/1.getting-started/02.using-tweek.md
  e2e/ui/package.json
  e2e/ui/pages/Settings/Policies.js
  e2e/ui/pages/Settings/index.js
  e2e/ui/spec/settings/edit-policies.js
  e2e/ui/yarn.lock
  package.json
  services/editor/package.json
  services/editor/src/Routes.js
  services/editor/src/components/UserBar.js
  services/editor/src/index.js
  services/editor/src/pages/settings/components/PoliciesPage/ACL.js
  services/editor/src/pages/settings/components/PoliciesPage/JWTExtraction.js
  services/editor/src/pages/settings/components/PoliciesPage/PoliciesPage.js
  services/editor/src/pages/settings/components/PoliciesPage/PoliciesPage.less
  services/editor/src/pages/settings/components/PoliciesPage/RemoteCodeEditor.js
  services/editor/src/pages/settings/components/PoliciesPage/acl-schema.json
  services/editor/src/pages/settings/components/PoliciesPage/utils.js
  services/editor/src/pages/settings/components/PoliciesPage/utils.spec.js
  services/editor/src/pages/settings/components/SettingsPage/IdentitiesMenu.js
  services/editor/src/pages/settings/components/SettingsPage/SettingsPage.js
  services/editor/src/store/ducks/notifications.js
  services/editor/src/store/index.js
  services/editor/src/utils/tweekClients.js
  services/editor/yarn.lock
Labels: in progress

#1117 Update acl-schema.json
  services/editor/package.json
  services/editor/src/pages/settings/components/PoliciesPage/acl-schema.json
Labels: in progress

#1116 Made uid of user git equal 1000
  TweekApi.Dockerfile
  services/api/Tweek.ApiService/Tweek.ApiService.csproj
  services/authoring/package.json
  services/authoring/yarn.lock
  services/publishing/Dockerfile
  services/publishing/Tweek.Publishing.Service/Tweek.Publishing.Service.csproj
Labels: in progress

#1119 Sanitized input in publishing
  e2e/ui/yarn.lock
  services/publishing/Tweek.Publishing.Service/Handlers/PushHandler.cs
  services/publishing/Tweek.Publishing.Service/Handlers/ValidationHandler.cs
  services/publishing/Tweek.Publishing.Service/Tweek.Publishing.Service.csproj
  services/publishing/Tweek.Publishing.Service/Utils/ShellHelper.cs
Labels: in progress
